import { cp, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = join(root, 'dist');
await mkdir(dist, { recursive: true });
await cp(join(root, 'src', 'index.d.ts'), join(dist, 'index.d.ts'));
await cp(join(root, 'src', 'detect.d.ts'), join(dist, 'detect.d.ts'));
await cp(join(root, 'src', 'errors.d.ts'), join(dist, 'errors.d.ts'));
await writeFile(join(dist, 'README.txt'), 'Generated by pnpm build. Runtime JavaScript is produced by Rspack 2.0.\n');
