import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = join(root, 'dist');
await mkdir(dist, { recursive: true });
await writeFile(join(dist, 'README.txt'), 'Generated by pnpm build. Runtime JavaScript is produced from TypeScript by Rspack 2.0; declarations are produced by tsc.\n');
